### ISSUE TITLE
window.game.destroyed() doesn't exists

### ISSUE THREAD

**Issue by wideLandscape** [ttzshawn/vue-phaser-starter#4]
in
[Home.vue](https://github.com/ttzshawn/vue-phaser-starter/blob/master/src/components/home/Home.vue)
there is an error exiting the route
```
  destroyed() {
    window.game.destroyed()
  },
```
replace with
```
  destroyed() {
     window.game.destroy()
  },
```
 and everything will be fine

**Comment by ttzshawn** [comment]
Thanks!
